
include: "data.smk"
include: "forecast.smk"
include: "reports.smk"

PREPROC_VARIANTS = ["standard", "scaled"]

rule all:
    input:
        expand("data/processed/preprocessing_dataset_{preproc}.csv", preproc=PREPROC_VARIANTS),
        expand("data/processed/train_{preproc}.csv", preproc=PREPROC_VARIANTS),
        expand("data/processed/test_{preproc}.csv", preproc=PREPROC_VARIANTS),
        expand("forecast/logistic_regression_{preproc}.csv", preproc=PREPROC_VARIANTS),
        expand("forecast/gradient_boosting_{preproc}.csv", preproc=PREPROC_VARIANTS),
        expand("forecast/random_forest_{preproc}.csv", preproc=PREPROC_VARIANTS),
        expand("reports/all_scores_{preproc}.csv", preproc=PREPROC_VARIANTS),
        "reports/comparison_titanic.csv"