
include: "data.smk"
include: "forecast.smk"
include: "reports.smk"

rule all:
    input:
        "data/processed/train_titanic.csv",
        "data/processed/test_titanic.csv",
        "forecast/logistic_regression_titanic.csv",
        "forecast/gradient_boosting_titanic.csv",
        "reports/all_scores_titanic.csv"
